### ISSUE TITLE
Get link endpoint

### ISSUE THREAD

**Issue by balessan** [oceanprotocol/decentralized_storage_backend#12]
# GetLink

**Description:**  Gets DDO files object for a job

**Path:**  GET /link?quoteId=xxx&nonce=1&signature=0xXXXXX

**Input:**  
- quoteId
- nonce  (timestamp)  (has to be higher then previous stored nonce for this user)
- signature:  user signed hash of SHA256(quoteID+nonce)

**Returns:**
```json
[
    {
       "type": "filecoin",
       "CID": "xxxx",
       "dealIDs":["x" , "x2"]
    }
]
```
(see https://docs.oceanprotocol.com/core-concepts/did-ddo#files  for how each microservice is formatting the response, based on storage type)

**Comment by balessan** [comment]
@happy-dev @alexcos20 I do not get this sentence:

> (see https://docs.oceanprotocol.com/core-concepts/did-ddo#files for how each microservice is formatting the response, based on storage type)

Is that unpredictable ?

In the example above, what are `"dealIDs":["x" , "x2"]` ? Is that of any interest ?

**Comment by happy-dev** [comment]
Sorry hadn't seen that one. Tell me if you need me to look at the DDO spec and summarize it for you
