### ISSUE TITLE
Prepare the docker-compose for complete environment

### ISSUE THREAD

**Issue by balessan** [oceanprotocol/decentralized_storage_backend#29]
To be able to deploy the project with its dependencies (like IPFS cluster, and associated micro-services) we should build a docker-compose agreggating all the proper containers and their configurations for a containerized deployment.

Could mean implement a Dockerfile and build/publish an image for all the individual micro-service.

**Comment by alexcos20** [comment]
I will add them to our barge

**Comment by balessan** [comment]
The #38 PR once merged will add that.
