### ISSUE TITLE
Clarify responsibilities between the front and the API

### ISSUE THREAD

**Issue by balessan** [oceanprotocol/decentralized_storage_backend#40]
More of a final specification ticket, than really a bug. There are a few topics not covered in the initial specification and covered in the current code using either environment variables or static keys, which does not make sense:

- User authentication
- Signature computation
- Transaction allowance validation
- Contracts information retrieval:
   - especially the ABI, used to generate the allowance

I initially thought about integrating mutiple new packages/API to handle those, like:

- https://github.com/wassafshahzad/django-metamask-auth#metamask-authentication for the user authentication part
- https://docs.etherscan.io/api-endpoints/ or https://github.com/pcko1/etherscan-python to retrieve proper informations about the actual contracts

But I am actually wondering if those process are the DBS or the client application reponsibility ?

Need additional inputs here.

**Comment by jamiehewitt15** [comment]
The signatures will be handled by the client side of the application. @EnzoVezzaro is working on the UI at the moment, it should be ready soon

**Comment by EnzoVezzaro** [comment]
I'm working on the dbs.js integration right now into the UI lib. I'll keep you posted.

**Comment by balessan** [comment]
> I'm working on the dbs.js integration right now into the UI lib. I'll keep you posted.

Ok. So just to be clear, can I consider that the client will manage:

- User authentication
- Signature computation
- Transaction allowance validation
- Contracts information retrieval:
   - Especially the ABI, used to generate the allowance

Because if so, I can simplify the code once more and consider to be just a proxy.

**Comment by jamiehewitt15** [comment]
Yeah @balessan this repo is really just meant to be a proxy. It doesn't need to handle: 

- User authentication
- Signature computation
- Transaction allowance validation
- Contracts information retrieval

I suggest that we close this issue and create separate issues to remove any unnecessary code that's still present.

**Comment by balessan** [comment]
Let's close it then.

**Comment by balessan** [comment]
> Thanks @balessan, can you create an issue for simplifying the code like you mentioned above, removing any unnecessary code

Opened as #80 to double-check that nothing unusual remains.
