### ISSUE TITLE
Deploy DBS components on our infrastructure

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/decentralized_storage_backend#41]

**Comment by md00ux** [comment]
deployed the following components:

- dbs (`oceanprotocol/dbs:next`)
- dbs_filecoin (`oceanprotocol/dbs_filecoin:next`)
- dbs_arweave (`oceanprotocol/dbs_arweave:next`)

URL: https://dbs.oceanprotocol.com

**Comment by EnzoVezzaro** [comment]
this is done, right? @jamiehewitt15 @md00ux 

can we close this issue?
