### ISSUE TITLE
cors issues with frontend

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/decentralized_storage_backend#44]
**Describe the bug**
when trying to access to the DBS endpoint, I get the following error:

`Access to XMLHttpRequest at 'http://localhost:8000/' from origin 'http://localhost:6006' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

this needs to be handle server-side to allow all origins to access the DBS server. 

It can be overcome by using a CORS unblocker like [CORS Unblock extension](https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino/related)

**Comment by mihaisc** [comment]
https://www.geeksforgeeks.org/how-to-enable-cors-headers-in-your-django-project/

**Comment by EnzoVezzaro** [comment]
hi @mariacarmina, how is this task going? did you have the chance to take a look at it? 

we're getting ready for the first release of dbs ui, this might become a blocker. I'll let you know once we're live 👍🏽

**Comment by mariacarmina** [comment]
I am working on it with priority.
