### ISSUE TITLE
Update the DBS to serve testing networks or production networks

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/decentralized_storage_backend#47]
Right now, DBS serves both testing and production networks. @alexcos20 pointed out that it would be better to have one that serves test networks and one that serves production networks

**Comment by jamiehewitt15** [comment]
It would be better to handle this at the microservice level as they are the ones that transfer the payment

**Comment by jamiehewitt15** [comment]
Closing this in favour of these two issues: 
https://github.com/oceanprotocol/dbs_filecoin/issues/43
https://github.com/oceanprotocol/dbs_arweave/pull/32
