### ISSUE TITLE
Vulnerable to malicious microservices

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/decentralized_storage_backend#55]
Right now anyone can call the register endpoint and register their own microservice. There are no checks on the microservice, as long as the request is sent in the right format the microservice gets registered. This seems to be a security vulnerability - anyone could register a malicious microservice which could take funds from the user without paying for any storage.

**Comment by EnzoVezzaro** [comment]
I agree, what do you think @alexcos20?

**Comment by jamiehewitt15** [comment]
The plan on this is to have each microservice sign a message and then the DBS will verify the signature of the microservice. There will be a list of allowed addresses in the DBS env. The microservice address will need to be in this env in order to register.

**Comment by jamiehewitt15** [comment]
This is done
