### ISSUE TITLE
historyList endpoint issues

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/decentralized_storage_backend#63]
**Describe the bug**
While using the historyList in the frontend I notice a couple of things:

- ~~the arweave array is empty. First array in the response, I should see a bunch of quotes from my wallet address.~~
- ~~the endpoint is returning a bunch of filecoin quotes I haven't created (I'm not using filecoin since we're waiting for the API updates). Are we sure is filtering by wallet address? can we just make a quick check please.~~ Now it is
- ~~on the response there's no CID (filecoin) or Transaction Hash (arweave)~~ (this seems ok on arweave, we need to check filecoin after updating the API)
- ~~on the response there's no Status Code~~ (this seems ok on arweave, we need to check filecoin after updating the API)
- ~~is not filtered by microservice (we need to filter the response by microservice)~~ created 
- ~~limit the response to the lastest 25 entry for now (and start thinking about the pagination for next sprints)~~ Fixed and created issue for pagination https://github.com/oceanprotocol/decentralized_storage_backend/issues/66

Here is what I get:

`
[
    [], //. this is empty for some reason
    {
        "data": [
            {
                "type": "filecoin",
                "quoteId": "009b8cc6314b4957a8d3bf47f5a2aefd",
                "tokenAmount": "1018",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-08-11T12:29:39.000Z",
                "updatedAt": "2023-08-11T12:29:39.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "034ef705bf9f45429efc42793899f52d",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T13:42:07.000Z",
                "updatedAt": "2023-07-27T13:42:07.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "03dac4aeccf74946b39533bb767b77dd",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T12:46:58.000Z",
                "updatedAt": "2023-07-27T12:46:58.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "08b10011e5c14691bb1ef5f6c0c2ece7",
                "tokenAmount": "3413",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-28T12:24:00.000Z",
                "updatedAt": "2023-07-28T12:24:00.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "13306fd7bd1440789a3d66418d7677b9",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T20:00:45.000Z",
                "updatedAt": "2023-07-27T20:00:45.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "22317fcc854345da89006a4ee468b4d8",
                "tokenAmount": "10923",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-25T23:53:34.000Z",
                "updatedAt": "2023-07-25T23:53:34.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "2272bb84d5c140859d73deafd39d9d23",
                "tokenAmount": "1018",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-08-15T19:05:32.000Z",
                "updatedAt": "2023-08-15T19:05:32.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "238075cc5677450a94ec3aa3be81ad29",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T18:46:42.000Z",
                "updatedAt": "2023-07-27T18:46:42.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "266306819c1548d28de9a91a64e8a4d3",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T15:00:47.000Z",
                "updatedAt": "2023-07-27T15:00:47.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "34e56051e5204aedab66f8c704a7aa7f",
                "tokenAmount": "1018",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-08-15T18:52:19.000Z",
                "updatedAt": "2023-08-15T18:52:19.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "3a65f8539d594a3983a8ff337e4acd86",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T20:03:15.000Z",
                "updatedAt": "2023-07-27T20:03:15.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "48a5c5ca2c8c4a7b9f94ea0d5d5ddb22",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T14:52:09.000Z",
                "updatedAt": "2023-07-27T14:52:09.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "4a24dc7bb25149418fd5a47b4bbf639c",
                "tokenAmount": "615",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-26T19:47:44.000Z",
                "updatedAt": "2023-07-26T19:47:44.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "6c0876ae70d64a1698b6572c8a97b7e3",
                "tokenAmount": "1597",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T20:07:26.000Z",
                "updatedAt": "2023-07-27T20:07:26.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "762928e546e54ecc9bd6fccb8432f3c6",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T14:53:30.000Z",
                "updatedAt": "2023-07-27T14:53:30.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "78959b7f49f848ca99a1a31aa4d16830",
                "tokenAmount": "21825",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x21c561e551638401b937b03fe5a0a0652b99b7dd",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-25T16:07:48.000Z",
                "updatedAt": "2023-07-25T16:07:48.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "796da54363d642cd95810dbac8c68dee",
                "tokenAmount": "1018",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-08-15T19:23:17.000Z",
                "updatedAt": "2023-08-15T19:23:17.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "839780b66e27455a8c3d97d05c41c0a9",
                "tokenAmount": "1018",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-08-15T18:52:41.000Z",
                "updatedAt": "2023-08-15T18:52:41.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "8c17c0c369b64a469763be6dc80ac854",
                "tokenAmount": "749",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x9aa7fec87ca69695dd1f879567ccf49f3ba417e2",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T20:03:29.000Z",
                "updatedAt": "2023-07-27T20:03:29.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "8f5cc6c694b440318b25ae1c8df8c01e",
                "tokenAmount": "3413",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-28T15:27:48.000Z",
                "updatedAt": "2023-07-28T15:27:48.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "8fdc611ecc3b4e80a9bb756e535c1a18",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T19:56:43.000Z",
                "updatedAt": "2023-07-27T19:56:43.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "961751c7b5f1411cbb4e38fdf7b57acc",
                "tokenAmount": "3413",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-28T15:16:47.000Z",
                "updatedAt": "2023-07-28T15:16:47.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "9987c8efe87e4b71b3504af88893c76c",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T20:02:56.000Z",
                "updatedAt": "2023-07-27T20:02:56.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "9e6d0eba4b2d47e19d7ddb7e494d8676",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T14:51:06.000Z",
                "updatedAt": "2023-07-27T14:51:06.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "b050259bdc894bd3860c6a4cb2934624",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T18:45:44.000Z",
                "updatedAt": "2023-07-27T18:45:44.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "b611591cdea74d21b3b0818c2e963e0a",
                "tokenAmount": "1018",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-08-11T12:28:37.000Z",
                "updatedAt": "2023-08-11T12:28:37.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "bdb9bd2cf7a843d9a6df57e751f98bac",
                "tokenAmount": "1018",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-08-15T19:11:00.000Z",
                "updatedAt": "2023-08-15T19:11:00.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "c8924b697f3c488985b3c8e3244f0e5a",
                "tokenAmount": "21825",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x21c561e551638401b937b03fe5a0a0652b99b7dd",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-25T14:13:08.000Z",
                "updatedAt": "2023-07-25T14:13:08.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "d4d5c0b02b0746c9a5cec4b37e653a3f",
                "tokenAmount": "108",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-28T12:05:07.000Z",
                "updatedAt": "2023-07-28T12:05:07.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "dbb00d38c2674058b858e6c43916f50e",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T19:01:07.000Z",
                "updatedAt": "2023-07-27T19:01:07.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "e45bd71565f9416f9500873931d662c7",
                "tokenAmount": "1597",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T14:44:58.000Z",
                "updatedAt": "2023-07-27T14:44:58.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "ec9c1e744f97499eabf6d9edf62200e5",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T18:39:53.000Z",
                "updatedAt": "2023-07-27T18:39:53.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "f397d4476c2a4bf08946bcaf2c4cdecb",
                "tokenAmount": "794",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T13:09:09.000Z",
                "updatedAt": "2023-07-27T13:09:09.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "f4e1020a7c264036b313c3938c371081",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T18:48:08.000Z",
                "updatedAt": "2023-07-27T18:48:08.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "f806bcc3de8b4f9e8baeb5e336ac6c39",
                "tokenAmount": "674",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-08-08T14:32:30.000Z",
                "updatedAt": "2023-08-08T14:32:30.000Z"
            },
            {
                "type": "filecoin",
                "quoteId": "fe1f4ea722874848bb636e02d6962f14",
                "tokenAmount": "750",
                "approveAddress": "0x0ff9092e55d9f6CCB0DD4C490754811bc0839866",
                "tokenAddress": "0x742dfa5aa70a8212857966d491d67b09ce7d6ec7",
                "chainId": 80001,
                "requestID": null,
                "isUsed": false,
                "createdAt": "2023-07-27T19:35:13.000Z",
                "updatedAt": "2023-07-27T19:35:13.000Z"
            }
        ]
    }
]
`

**Comment by jamiehewitt15** [comment]
That's interesting that you don't get any response from the arweave microservice. THis is what I'm getting:

```
[
  [
    {
      type: 'arweave',
      quoteId: '290e598a1d548184f682f0e3d7029de7',
      status: 1,
      chainId: 80001,
      tokenAddress: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889',
      tokenAmount: '821595376359550',
      approveAddress: '0x5F8396D1BfDa5259Ee89196F892E4401BF3B596d',
      transactionHash: null
    },
    {
      type: 'arweave',
      quoteId: '290e598a1d548184f682f0e3d7029de7',
      status: 1,
      chainId: 80001,
      tokenAddress: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889',
      tokenAmount: '821595376359550',
      approveAddress: '0x5F8396D1BfDa5259Ee89196F892E4401BF3B596d',
      transactionHash: null
    },
    {
      type: 'arweave',
      quoteId: 'e5d57d85408ae22e2aa5b5ee9b17bc32',
      status: 1,
      chainId: 80001,
      tokenAddress: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889',
      tokenAmount: '821595376010298',
      approveAddress: '0x5F8396D1BfDa5259Ee89196F892E4401BF3B596d',
      transactionHash: null
    },
    {
      type: 'arweave',
      quoteId: 'e5d57d85408ae22e2aa5b5ee9b17bc32',
      status: 1,
      chainId: 80001,
      tokenAddress: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889',
      tokenAmount: '821595376010298',
      approveAddress: '0x5F8396D1BfDa5259Ee89196F892E4401BF3B596d',
      transactionHash: null
    },
    {
      type: 'arweave',
      quoteId: '586cce5c31a89fe2c23ceaac972fe761',
      status: 404,
      chainId: 80001,
      tokenAddress: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889',
      tokenAmount: '821595376010298',
      approveAddress: '0x5F8396D1BfDa5259Ee89196F892E4401BF3B596d',
      transactionHash: 'iyAye17xIUnOBuHeuCvWC9pzxe6t1N84yb_2Sm8pC1I'
    },
    {
      type: 'arweave',
      quoteId: '586cce5c31a89fe2c23ceaac972fe761',
      status: 404,
      chainId: 80001,
      tokenAddress: '0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889',
      tokenAmount: '821595376010298',
      approveAddress: '0x5F8396D1BfDa5259Ee89196F892E4401BF3B596d',
      transactionHash: null
    }
  ],
  {
    data: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 64 more items
    ]
  }
]
```

**Comment by EnzoVezzaro** [comment]
interesting, now I'm getting a response: 

<img width="960" alt="Screenshot 2023-08-17 at 10 03 53" src="https://github.com/oceanprotocol/decentralized_storage_backend/assets/13741335/6fa4a8fa-8f74-4d50-87bd-6ffd56f13cd1">

if It happens again, I'll post it here 👍🏽

**Comment by mariacarmina** [comment]
Regarding `is not filtered by microservice (we need to filter the response by microservice)`, @alexcos20 suggested that in DBS app we should merge the lists (from microservices) and send to frontend. @alexcos20 can you confirm?

**Comment by mariacarmina** [comment]
Updated description, all points from this issue description are handled and `/getHistory` endpoint works as expected.
