### ISSUE TITLE
Debug and fix file upload (>1MB) on the DBS

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/decentralized_storage_backend#73]

**Comment by mariacarmina** [comment]
After some investigations, in frontend we received 413 error which means `Content Too Large` from Django side. An hypothesis could be that `client_max_body_size` needs to be increased in the nginx configuration for django server as [it is highlighted in this article](https://stackoverflow.com/questions/36994828/413-request-entity-too-large-nginx-django).

**Comment by mariacarmina** [comment]
The issue is fixed because the nginx configurations for Django server needed to be increased and now the upload for files larger than 1 Mb works. Tested with 86 Mb file and it worked.
