### ISSUE TITLE
Quote creation endpoint

### ISSUE THREAD

**Issue by balessan** [oceanprotocol/decentralized_storage_backend#9]
# Quote creation endpoint definition

**Description:**  Gets a quote in order to store some files on a specific storage

**Path:**  POST /quotes/

**Arguments:**  
```json
{
    "type": "filecoin",
    "files": [
                {"length":2343545},
                {"length":2343545},
            ],
    "duration": 4353545453
    "payment": {
        "chainId": 1,
        "tokenAddress": "0xOCEAN_on_MAINNET"
    },
    "userAddress": "0x456"
}
```
**Where:**
- type:  type of storage desired
- files :  array with files length
- duration:  how long to store this files (in seconds)
- payment.chainId:  chainId that will be used to make the payment
- payment.token:  token that will be used to make the payment
- userAddress:  user who will pay

**Returns:**
```json
{
    "tokenAmount": 500,
    "approveAddress": "0x123",
    "chainId": 1,
    "tokenAddress": "0xOCEAN_on_MAINNET",
    "quoteId": "xxxx"
}  
```
**Where:**
- tokenAmount - tokenAmount that needs to be approved for "approveAddress" on tokenAddress  (backend server will do a transferFrom to get the payment)
- chainId - chainId used for payment
- quoteId  - backend server will generate a quoteId, used to upload, getStatus and getLink

**Comment by balessan** [comment]
@alexcos20 @happy-dev I am currently working on this implementation. But as far as I get it, once our public DBS API endpoint receives the call, it should actually request (for instance) the filecoin service API to get a quote there, but I cannot find any information on this API.

Do you have documentation entries/examples on tha ?

This question stands for all related services.

**Comment by balessan** [comment]
I guess I should make use of https://github.com/oceanprotocol/dbs_filecoin ?

**Comment by happy-dev** [comment]
Yes, have a look at issues #2, #3 and #4 here

They are all the same, call me if in doubt of anything
